name: Deploy Full MERN App

on:
  push:
    branches:
      - main      # Trigger on pushes to the main branch

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Login to Docker Hub
        run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}

      #############################
      #  FRONTEND BUILD & PUSH
      #############################
      - name: Build React Image
        run: |
          docker build -t jitendrajat/reactjs-app:latest \
            --build-arg REACT_APP_NODE_ENV=production \
            --build-arg REACT_APP_SERVER_BASE_URL="${{ secrets.REACT_APP_SERVER_BASE_URL }}" \
            ./frontend

      - name: Push React Image
        run: docker push jitendrajat/reactjs-app:latest

      #############################
      #  BACKEND BUILD & PUSH
      #############################
      - name: Build NodeJS Image
        run: |
          docker build -t jitendrajat/nodejs-app:latest \
            ./backend

      - name: Push NodeJS Image
        run: docker push jitendrajat/nodejs-app:latest


  deploy:
    needs: build
    runs-on: self-hosted  # Your EC2 runner

    steps:
      - name: Deploy BACKEND Container
        run: |
          docker pull jitendrajat/nodejs-app:latest
          docker rm -f nodejs-app-container || true
          docker run -d \
            -p 4000:4000 \
            --name nodejs-app-container \
            -e MONGO_USERNAME="${{ secrets.MONGO_USERNAME }}" \
            -e MONGO_PASSWORD="${{ secrets.MONGO_PASSWORD }}" \
            -e MONGO_HOST="${{ secrets.MONGO_HOST }}" \
            jitendrajat/nodejs-app:latest

      - name: Deploy FRONTEND Container
        run: |
          docker pull jitendrajat/reactjs-app:latest
          docker rm -f reactjs-app-container || true
          docker run -d \
            -p 3000:80 \
            --name reactjs-app-container \
            jitendrajat/reactjs-app:latest
